/* APSAN — correções ISOLADAS + apresentação completa do catálogo. */
(function(){
'use strict';
function fixMaterialButton(){const b=document.getElementById('apsanMatSubmit');if(!b)return;b.disabled=false;b.removeAttribute('disabled')}
function removeCloud(){/* Mantém o ícone/área de nuvem original. Nada é ocultado. */}
function fixTurmas(){const b=document.getElementById('apsanLiveNavBtn');if(!b||b.dataset.apsanSafeBound==='1')return;b.dataset.apsanSafeBound='1';b.type='button';b.addEventListener('click',function(e){e.preventDefault();e.stopPropagation();try{if(typeof window.apsanRenderLiveClasses==='function'){window.apsanRenderLiveClasses();return}if(typeof window.renderClasses==='function'){window.renderClasses();return}if(!document.getElementById('apsanLiveClassroomRecovery')){const s=document.createElement('script');s.id='apsanLiveClassroomRecovery';s.src='js/live-classroom.js?v=20260906c';s.async=false;s.onload=function(){try{window.apsanRenderLiveClasses?.()}catch(err){console.error(err)}};document.head.appendChild(s)}}catch(err){console.error('APSAN Turmas:',err)}},false)}
function loadPhysicalMarketplace(){if(document.getElementById('apsanPhysicalMarketplaceLoader'))return;const s=document.createElement('script');s.id='apsanPhysicalMarketplaceLoader';s.src='js/physical-marketplace.js?v=20260907a';s.async=false;s.onload=function(){try{loadPhysicalAdmin()}catch(e){}};s.onerror=function(){console.error('APSAN: não foi possível carregar o Marketplace físico.')};document.head.appendChild(s)}
function loadPhysicalAdmin(){if(document.getElementById('apsanPhysicalAdminLoader'))return;const s=document.createElement('script');s.id='apsanPhysicalAdminLoader';s.src='js/physical-admin-layer.js?v=20260907b';s.async=false;s.onerror=function(){console.error('APSAN: não foi possível carregar a camada administrativa do Marketplace físico.')};document.head.appendChild(s)}
function loadAccountRegistrationFix(){if(document.getElementById('apsanAccountRegistrationFixLoader'))return;const s=document.createElement('script');s.id='apsanAccountRegistrationFixLoader';s.src='js/account-registration-fix.js?v=20260907a';s.async=false;s.onerror=function(){console.error('APSAN: não foi possível carregar a correção de criação de contas.')};document.head.appendChild(s)}
function loadProductDetailsFix(){if(document.getElementById('apsanProductDetailsFixLoader'))return;const s=document.createElement('script');s.id='apsanProductDetailsFixLoader';s.src='js/product-details-fix.js?v=20260908a';s.async=false;s.onload=function(){setTimeout(enhanceCatalog,50)};s.onerror=function(){console.error('APSAN: não foi possível carregar a correção de detalhes dos produtos.')};document.head.appendChild(s)}
function loadDeliveryTimeFix(){if(document.getElementById('apsanDeliveryTimeFixLoader'))return;const s=document.createElement('script');s.id='apsanDeliveryTimeFixLoader';s.src='js/delivery-time-fix.js?v=20260908c';s.async=false;s.onerror=function(){console.error('APSAN: não foi possível carregar a integração de prazos de entrega.')};document.head.appendChild(s)}
function loadDeliveryTransportPolicy(){if(document.getElementById('apsanDeliveryTransportPolicyLoader'))return;const s=document.createElement('script');s.id='apsanDeliveryTransportPolicyLoader';s.src='js/delivery-transport-policy.js?v=20260908b';s.async=false;s.onerror=function(){console.error('APSAN: não foi possível carregar a política automática de prazos e transportes.')};document.head.appendChild(s)}
function loadRestoreExistingCatalog(){if(document.getElementById('apsanRestoreExistingCatalogLoader'))return;const s=document.createElement('script');s.id='apsanRestoreExistingCatalogLoader';s.src='js/restore-existing-catalog.js?v=20260909a';s.async=false;s.onerror=function(){console.error('APSAN: não foi possível carregar a restauração do catálogo existente.')};document.head.appendChild(s)}

const PK='apsan_produtos';
function data(){try{return typeof getData==='function'?(getData(PK)||[]):JSON.parse(localStorage.getItem(PK)||'[]')}catch(e){return[]}}
function save(a){try{if(typeof setData==='function')setData(PK,a);else localStorage.setItem(PK,JSON.stringify(a))}catch(e){console.error('APSAN catálogo',e)}}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function money(v){const n=Number(v);if(!Number.isFinite(n))return'';try{return new Intl.NumberFormat('pt-AO',{style:'currency',currency:'AOA',maximumFractionDigits:0}).format(n)}catch(e){return n.toLocaleString('pt-AO')+' Kz'}}
function findProduct(card){const all=data().filter(p=>p&&!p.deleted&&(p.status==='approved'||p.isPublished===true));const id=card?.getAttribute('data-product-id')||card?.getAttribute('data-product')||card?.getAttribute('data-id');if(id){const p=all.find(x=>String(x.id)===String(id));if(p)return p}const text=(card?.textContent||'').replace(/\s+/g,' ').toLowerCase();return all.find(p=>p.name&&text.includes(String(p.name).toLowerCase()))||null}
function enhanceCards(){document.querySelectorAll('.product-card,.product-item,.product,.marketplace-product,.product-box,.product-card-modern,[data-product-id],[data-product]').forEach(card=>{if(card.dataset.apsanCardInfo==='1')return;const p=findProduct(card);if(!p)return;const hasDiscount=p.promoPrice!==null&&p.promoPrice!==undefined&&p.promoPrice!==''&&Number(p.promoPrice)<Number(p.realPrice),pct=hasDiscount&&Number(p.realPrice)>0?Math.round((1-Number(p.promoPrice)/Number(p.realPrice))*100):0,loc=[p.province,p.municipality,p.location].filter(Boolean).join(' — '),stock=Number.isFinite(Number(p.stock))?Number(p.stock):null;const parts=[];if(loc)parts.push('<div><span>📍</span><strong>Local:</strong> '+esc(loc)+'</div>');if(hasDiscount)parts.push('<div><span>🏷️</span><strong>Desconto:</strong> <b class="apsan-card-discount">-'+pct+'%</b> · agora '+money(p.promoPrice)+'</div>');if(stock!==null)parts.push('<div><span>📦</span><strong>Stock:</strong> '+stock+' unidade'+(stock===1?'':'s')+' · '+(stock>0?'Em stock':'Esgotado')+'</div>');if(p.brand)parts.push('<div><span>🔖</span><strong>Marca:</strong> '+esc(p.brand)+'</div>');if(!parts.length)return;const box=document.createElement('div');box.className='apsan-card-product-info';box.innerHTML=parts.join('');const btn=Array.from(card.querySelectorAll('button,a,[role="button"]')).find(x=>/ver produto|ver mais|detalhes/i.test(x.textContent||''));if(btn)card.insertBefore(box,btn);else card.appendChild(box);card.dataset.apsanCardInfo='1'})}
function injectCharacteristics(){const form=document.getElementById('aptPhysicalForm');if(!form||form.querySelector('[name="characteristics"]'))return;const d=form.querySelector('[name="description"]')?.closest('.apt-field');const wrap=document.createElement('div');wrap.className='apt-field apt-full';wrap.innerHTML='<label>Características do produto *</label><textarea name="characteristics" required placeholder="Ex.: cor, tamanho, material, composição, funções, dimensões, capacidade e outras características importantes"></textarea>';if(d)d.after(wrap);else form.querySelector('.apt-grid-form')?.prepend(wrap);form.addEventListener('submit',function(){const value=wrap.querySelector('textarea').value.trim();window.__apsanProductCharacteristics=value;setTimeout(function(){try{const a=data(),p=a.filter(x=>x&&x.id&&String(x.id).startsWith('PROD-FIS-')).sort((x,y)=>String(y.createdAt||'').localeCompare(String(x.createdAt||'')))[0];if(p&&value){p.characteristics=value;save(a)}}catch(e){}},250)},true)}
function injectDetailCharacteristics(){const modal=document.getElementById('apsanProductDetailsModal');if(!modal||modal.querySelector('.apsan-characteristics-detail'))return;const buy=modal.querySelector('[data-buy]'),id=buy?.getAttribute('data-buy'),p=data().find(x=>String(x.id)===String(id));if(!p?.characteristics&&!p?.features)return;const sec=document.createElement('div');sec.className='apsan-characteristics-detail';sec.style.cssText='margin-top:18px;padding:16px;border:1px solid #e2e8f0;border-radius:14px;background:#f8fafc;color:#334155;line-height:1.65;white-space:pre-wrap';sec.innerHTML='<strong style="color:#0f172a">Características do produto</strong><br>'+esc(p.characteristics||p.features);const desc=modal.querySelector('.desc');if(desc)desc.before(sec);else modal.querySelector('.body')?.appendChild(sec)}
function addCatalogStyles(){if(document.getElementById('apsanCatalogEnhancementStyle'))return;const s=document.createElement('style');s.id='apsanCatalogEnhancementStyle';s.textContent='.apsan-card-product-info{margin:10px 0 12px;padding:10px 12px;border:1px solid #e2e8f0;border-radius:12px;background:#f8fafc;color:#334155;font-size:.9rem;line-height:1.55}.apsan-card-product-info>div{margin:3px 0}.apsan-card-product-info span{margin-right:5px}.apsan-card-product-info strong{color:#172033}.apsan-card-product-info del{color:#64748b;margin-left:5px}.apsan-card-discount{display:inline-block;margin-left:5px;padding:2px 6px;border-radius:6px;background:#dcfce7;color:#166534}.apsan-characteristics-detail{font-size:.96rem}@media(max-width:600px){.apsan-card-product-info{font-size:.86rem}}';document.head.appendChild(s)}
function enhanceCatalog(){addCatalogStyles();enhanceCards();injectCharacteristics();injectDetailCharacteristics()}
function scan(){removeCloud();fixMaterialButton();fixTurmas();loadPhysicalMarketplace();loadPhysicalAdmin();loadAccountRegistrationFix();loadProductDetailsFix();loadDeliveryTimeFix();loadDeliveryTransportPolicy();loadRestoreExistingCatalog();enhanceCatalog()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',scan,{once:true});else scan();new MutationObserver(scan).observe(document.documentElement,{childList:true,subtree:true});setInterval(scan,800)
})();
