/* APSAN — correções ISOLADAS de Turmas, Publicar material, Marketplace físico, contas, detalhes e logística. */
(function(){
'use strict';
function fixMaterialButton(){const b=document.getElementById('apsanMatSubmit');if(!b)return;b.disabled=false;b.removeAttribute('disabled')}
function removeCloud(){if(document.getElementById('apsanButtonsFixStyle'))return;const s=document.createElement('style');s.id='apsanButtonsFixStyle';s.textContent='.apsan-mat-drop > i{display:none!important}.apsan-mat-drop .fa-cloud,.apsan-mat-drop .fa-cloud-arrow-up{display:none!important}';document.head.appendChild(s)}
function fixTurmas(){const b=document.getElementById('apsanLiveNavBtn');if(!b||b.dataset.apsanSafeBound==='1')return;b.dataset.apsanSafeBound='1';b.type='button';b.addEventListener('click',function(e){e.preventDefault();e.stopPropagation();try{if(typeof window.apsanRenderLiveClasses==='function'){window.apsanRenderLiveClasses();return}if(typeof window.renderClasses==='function'){window.renderClasses();return}if(!document.getElementById('apsanLiveClassroomRecovery')){const s=document.createElement('script');s.id='apsanLiveClassroomRecovery';s.src='js/live-classroom.js?v=20260906c';s.async=false;s.onload=function(){try{window.apsanRenderLiveClasses?.()}catch(err){console.error(err)}};document.head.appendChild(s)}}catch(err){console.error('APSAN Turmas:',err)}},false)}
function loadPhysicalMarketplace(){if(document.getElementById('apsanPhysicalMarketplaceLoader'))return;const s=document.createElement('script');s.id='apsanPhysicalMarketplaceLoader';s.src='js/physical-marketplace.js?v=20260907a';s.async=false;s.onload=function(){try{loadPhysicalAdmin()}catch(e){}};s.onerror=function(){console.error('APSAN: não foi possível carregar o Marketplace físico.')};document.head.appendChild(s)}
function loadPhysicalAdmin(){if(document.getElementById('apsanPhysicalAdminLoader'))return;const s=document.createElement('script');s.id='apsanPhysicalAdminLoader';s.src='js/physical-admin-layer.js?v=20260907b';s.async=false;s.onerror=function(){console.error('APSAN: não foi possível carregar a camada administrativa do Marketplace físico.')};document.head.appendChild(s)}
function loadAccountRegistrationFix(){if(document.getElementById('apsanAccountRegistrationFixLoader'))return;const s=document.createElement('script');s.id='apsanAccountRegistrationFixLoader';s.src='js/account-registration-fix.js?v=20260907a';s.async=false;s.onerror=function(){console.error('APSAN: não foi possível carregar a correção de criação de contas.')};document.head.appendChild(s)}
function loadProductDetailsFix(){if(document.getElementById('apsanProductDetailsFixLoader'))return;const s=document.createElement('script');s.id='apsanProductDetailsFixLoader';s.src='js/product-details-fix.js?v=20260908a';s.async=false;s.onerror=function(){console.error('APSAN: não foi possível carregar a correção de detalhes dos produtos.')};document.head.appendChild(s)}
function loadDeliveryTimeFix(){if(document.getElementById('apsanDeliveryTimeFixLoader'))return;const s=document.createElement('script');s.id='apsanDeliveryTimeFixLoader';s.src='js/delivery-time-fix.js?v=20260908c';s.async=false;s.onerror=function(){console.error('APSAN: não foi possível carregar a integração de prazos de entrega.')};document.head.appendChild(s)}
function loadDeliveryTransportPolicy(){if(document.getElementById('apsanDeliveryTransportPolicyLoader'))return;const s=document.createElement('script');s.id='apsanDeliveryTransportPolicyLoader';s.src='js/delivery-transport-policy.js?v=20260908b';s.async=false;s.onerror=function(){console.error('APSAN: não foi possível carregar a política automática de prazos e transportes.')};document.head.appendChild(s)}
function scan(){removeCloud();fixMaterialButton();fixTurmas();loadPhysicalMarketplace();loadPhysicalAdmin();loadAccountRegistrationFix();loadProductDetailsFix();loadDeliveryTimeFix();loadDeliveryTransportPolicy()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',scan,{once:true});else scan();new MutationObserver(scan).observe(document.documentElement,{childList:true,subtree:true});setInterval(scan,800)
})();
